### ISSUE TITLE
This is a new demo issue

### ISSUE THREAD

**Issue by cdupuis** [atomisthqa/handlers#107]

**Comment by slimslenderslacks** [comment]
Okay, I'm looking at this now ... will assign in a second

**Comment by cdupuis** [comment]
Thanks for taking the lead here.

**Comment by slimslenderslacks** [comment]
well, actually, we should get <@U1NNAQKEH> opinion as well

**Comment by cdupuis** [comment]
Puh, fixed the build after all.
