### ISSUE TITLE
Lets make a major change

### ISSUE THREAD

**Issue by cdupuis** [atomisthqa/handlers#141]

**Comment by cdupuis** [comment]
Oh. Friday is best for that.

**Comment by slimslenderslacks** [comment]
Okay, it's assigned to me and I think I know what the problem is.

**Comment by jessitron** [comment]
no way

**Comment by jessitron** [comment]
how about now

**Comment by cdupuis** [comment]
This is my awesome event

**Comment by jessitron** [comment]
is the formatting better? Try making your own comment here please
