### ISSUE TITLE
This is my test of something new

### ISSUE THREAD

**Issue by cdupuis** [atomisthqa/handlers#708]
Hey @slimslenderslacks are you getting this?

cc @cdupuis

**Comment by cdupuis** [comment]
some more tests 
@cdupuis, @tanya-coding, @whostolebenfrog

**Comment by cdupuis** [comment]
@cdupuis @slimslenderslacks

**Comment by whostolebenfrog** [comment]
@cdupuis I hear you

**Comment by cdupuis** [comment]
@slimslenderslacks

**Comment by cdupuis** [comment]
are you getting this via a @atomist dm @whostolebenfrog?

**Comment by whostolebenfrog** [comment]
No, sadly not. via github

**Comment by whostolebenfrog** [comment]
@cd Might work now though - fixed the multi ChatId issue in staging which may have been causing it to break. Or it might have been something else of course!
